language: android
android:
  components:
    - build-tools-25.0.1
    - android-25

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches

script:
  - ./gradlew core:cleanTest core:test
  - ./gradlew desktop:dist
  - ./gradlew android:assembleRelease
