language: android
android:
  components:
    - build-tools-27.0.3
    - android-27

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches

script:
  - ./gradlew core:cleanTest core:test
  - ./gradlew desktop:dist
  - ./gradlew android:assembleRelease
